spin_manifest_version = 2

[application]
name = "travel-helper"
version = "0.1.0"
authors = ["Rohit Dandamudi <rohitdandamudi.1100@gmail.com>"]
description = ""

[[trigger.http]]
route = "/plan-my-trip/..."
component = "travel-helper"

[component.travel-helper]
source = "target/wasm32-wasi/release/travel_helper.wasm"
allowed_outbound_hosts = []
ai_models = ["llama2-chat"]
key_value_stores = ["default"]
[component.travel-helper.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
